# Generated by Django 5.1.1 on 2024-11-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="catagory",
            new_name="Brand",
        ),
        migrations.RenameField(
            model_name="brand",
            old_name="catagoryName",
            new_name="brandName",
        ),
    ]
