# Generated by Django 5.1.1 on 2024-11-16 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_rename_catagory_brand_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listings",
            name="catagory",
        ),
        migrations.AddField(
            model_name="listings",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand",
                to="auctions.brand",
            ),
        ),
    ]
