# Generated by Django 5.1.1 on 2024-11-18 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_listings_watchlist_bid_alter_listings_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_price",
                to="auctions.bid",
            ),
        ),
    ]
